code --install-extension ms-python.python
code --install-extension ms-vscode.go
code --install-extension amodio.gitlens
code --install-extension vscodevim.vim
code --install-extension njpwerner.autodocstring
code --install-extension formulahendry.code-runner
code --install-extension ms-python.anaconda-extension-pack
code --install-extension aaron-bond.better-comments
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-pack